/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.util.LinkedList;

import javax.swing.table.DefaultTableModel;

import databaseIO.Query;
import databaseIO.Table;
import luncher.App;

/**
 *
 * @author Abtuly
 */
public class InsetionUI extends javax.swing.JFrame {

   /**
    * Creates new form insetDilog
    */
   public InsetionUI(Table table) {
      this.selectedTable = table;

      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */

   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      insetionData = new javax.swing.JTable();
      cancelBtn = new javax.swing.JButton();
      exexuteBtn = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      DefaultTableModel model = new DefaultTableModel(this.selectedTable.getColumnNames().toArray(), 10);
      this.insetionData.setModel(model);

      jScrollPane1.setViewportView(insetionData);

      cancelBtn.setText("Cancel");
      cancelBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelBtnActionPerformed(evt);
         }
      });

      exexuteBtn.setText("Execute");
      exexuteBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exexuteBtnActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(exexuteBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(174, 174, 174))
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
      layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(exexuteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)));
      initStyle();
      this.setVisible(true);
      pack();

   }// </editor-fold>

   private void exexuteBtnActionPerformed(java.awt.event.ActionEvent evt) {
      LinkedList<String> dataToInsert = new LinkedList<String>();
      for (int i = 0; i < this.insetionData.getModel().getRowCount(); i++) {
         for (int j = 0; j < this.insetionData.getModel().getColumnCount(); j++) {
            if (this.insetionData.getModel().getValueAt(i, j) != null) {
               // TODO alter when implement datatypes
               dataToInsert.add((String) this.insetionData.getModel().getValueAt(i, j));
               // System.out.println(this.insetionData.getModel().getValueAt(i, j));
            } else {
               dataToInsert.clear();
               break;
            }
         }
         if (!dataToInsert.isEmpty()) {
            String sql = "INSERT INTO " + selectedTable.getName() + " " + selectedTable.getColumnToInsertSQL()
                  + " values" + Query.listToInsertSQL(dataToInsert, selectedTable.getDataType());
            System.out.println(sql);

            Query.executeUpdate(sql);
         }

      }
   }

   private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
      

      this.dispose();
   }

   /**
    * @param args the command line arguments
    */
   public void initStyle() {

      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the default
       * look and feel.
       * For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(InsetionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(InsetionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(InsetionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(InsetionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      // </editor-fold>

      /* Create and display the form */
      // java.awt.EventQueue.invokeLater(new Runnable() {
      // public void run() {
      // new InsetionUI(selectedTable).setVisible(true);
      // }
      // });
   }

   // Variables declaration - do not modify
   private javax.swing.JButton cancelBtn;
   private javax.swing.JButton exexuteBtn;
   private javax.swing.JTable insetionData;
   private javax.swing.JScrollPane jScrollPane1;
   private Table selectedTable;
   // End of variables declaration
}
