/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;

import databaseIO.Query;

/**
 *
 * @author Abtuly
 */
public class login extends javax.swing.JFrame {

   /**
    * Creates new form login
    */
   public login() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */

   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

      jInternalFrame1 = new javax.swing.JInternalFrame();
      usernameLabel = new javax.swing.JLabel();
      passwordLabel = new javax.swing.JLabel();
      loginBtn = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      URLTextField = new javax.swing.JTextField();
      passwordTextField = new javax.swing.JPasswordField();
      usernameTextField = new javax.swing.JTextField();
      DBLabel = new javax.swing.JLabel();
      cancelBtn = new javax.swing.JButton();
      createAccountbtn = new javax.swing.JButton();

      jInternalFrame1.setVisible(true);

      javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
      jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
      jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 0, Short.MAX_VALUE));
      jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 0, Short.MAX_VALUE));

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);

      usernameLabel.setText("Username");

      passwordLabel.setText("Password");

      loginBtn.setText("Log in");
      loginBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            loginBtnActionPerformed(evt);
         }
      });

      URLTextField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            URLTextFieldActionPerformed(evt);
         }
      });

      usernameTextField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            usernameTextFieldActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(URLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE)));
      jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(URLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                              javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));

      DBLabel.setText("Database URL");

      cancelBtn.setText("cancel");
      cancelBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelBtnActionPerformed(evt);
         }
      });

      createAccountbtn.setText("sign in");
      createAccountbtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            createAccountbtnActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(DBLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                          javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createAccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                          javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(9, 9, 9)))
                        .addGap(34, 34, 34)));
      layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(DBLabel)
                                    .addGap(32, 32, 32)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28,
                                          Short.MAX_VALUE)
                                    .addGap(31, 31, 31)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                          javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addContainerGap(31, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(createAccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(54, Short.MAX_VALUE)));
                        this.setVisible(true);
      pack();
   }// </editor-fold>

   private void URLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
      // TODO add your handling code here:
   }

   private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
      // TODO add your handling code here:
   }

   private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {
    
   }

   private void createAccountbtnActionPerformed(java.awt.event.ActionEvent evt) {
      // TODO add your handling code here:
   }

   private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
      System.exit(ABORT);
   }

   /**
    * @param args the command line arguments
    */
   private static void run() {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the default
       * look and feel.
       * For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      // </editor-fold>

      /* Create and display the form */
      // java.awt.EventQueue.invokeLater(new Runnable() {
      //    public void run() {
      //       new login().setVisible(true);
      //    }
      // });
   }

   // Variables declaration - do not modify
   private javax.swing.JLabel DBLabel;
   private javax.swing.JTextField URLTextField;
   private javax.swing.JButton cancelBtn;
   private javax.swing.JButton createAccountbtn;
   private javax.swing.JInternalFrame jInternalFrame1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JButton loginBtn;
   private javax.swing.JLabel passwordLabel;
   private javax.swing.JPasswordField passwordTextField;
   private javax.swing.JLabel usernameLabel;
   private javax.swing.JTextField usernameTextField;
   // End of variables declaration
}
